name: Lint

on: pull_request

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build containers
        run: docker-compose build

      - name: Lint
        run: docker-compose run --rm app "yarn && yarn lint"

      - name: Format
        run: docker-compose run --rm app "yarn format:check"
